name: PR Test

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run build (clean verify)
        run: |
          if [ -f src/main/resources/application-ci.yml ]; then
            mvn clean verify \
              -Dspring.config.import=optional:classpath:/application-ci.yml \
              -Dspring.profiles.active=ci
          else
            mvn clean verify
          fi

  test-success:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Notify Success
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "✅ 테스트 성공!",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 테스트 성공",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "green"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"

  test-failure:
    needs: test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Notify Failure
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "❌ 테스트 실패...",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 테스트 실패",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "red"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"
