spring:
  application:
    name: batchservice
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  batch:
    job:
      enabled: false

dbcp2:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initial-size: 5
    max-total: 5
    max-idle: 5
    min-idle: 5
    between-eviction-millis: 300000
    min-evictable-idle-millis: 600000
    num-tests-per-eviction-run: 3

server:
  port: 10396
  shutdown: graceful

eureka:
  client:
    enabled: false

batch:
  schedule:
    update-user-grade: "0 0 0 1 * ?"
    update-user-state: "0 0 1 1 * ?"
