spring:
  application:
    name: batchservice
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

dbcp2:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initial-size: 5
    max-total: 5
    max-idle: 5
    min-idle: 5


server:
  port: 10396
  shutdown: graceful

eureka:
  client:
    enabled: false

# Order Payment
order:
  api:
    url: http://localhost:10392

# Book
book:
  api:
    url: http://localhost:10390

# Coupon
coupon:
  api:
    url: http://localhost:10388
